name: flutter_custom_calendar
description: A new Flutter Calendar package.
version: 0.0.2
author: vickyleu <yu6564172@gmail.com.com>
homepage: https://github.com/vickyleu/flutter_custom_calendar

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 3.0.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


